//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager.Models
{
    using InventoryManager.CustomValidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public int Id { get; set; }
        [Display(Name = "Product Name")]

        [Required(ErrorMessage = "Product Name is required")]
        public string Product_name { get; set; }

        [Required(ErrorMessage = "Product Quantity is required")]
        [Display(Name = "Product Quantity")]
        [IntegerString(ErrorMessage = "Product Quantity must be an integer")]
        public string Product_qnty { get; set; }
    }

}
