//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager.Models
{
    using InventoryManager.CustomValidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Sale Product")]
        public string Sale_prod { get; set; }

        [Required]
        [Display(Name = "Sale Quantity")]
        [IntegerString(ErrorMessage = "Sale Quantity must be an integer")]
        public string Sale_qunty { get; set; }

        [Required]
        [Display(Name = "Sale Date")]
        public System.DateTime Sale_date { get; set; }
    }
}
